const data = {
	products: [
		{
			name: 'Nike Solo Swoosh',
			slug: 'nike-solo-swoosh',
			category: 'Bomber Jacket',
			image: '/Images/bomber1.webp',
			price: 195,
			rating: 5,
			numReviews: 8,
			countInStock: 20,
			description: 'Bomber Jacket',
		},
		{
			name: 'Nike Repel Miler',
			slug: 'nike-repel-miler',
			category: 'Running Jacket',
			image: '/Images/runner1.webp',
			price: 90,
			rating: 4.8,
			numReviews: 3,
			countInStock: 20,
			description: 'Running Jacket',
		},
		{
			name: 'Nike Sportswear Circa',
			slug: 'nike-sportswear-circa',
			category: 'Lined Anorak',
			image: '/Images/lined1.webp',
			price: 124,
			rating: 3.5,
			numReviews: 16,
			countInStock: 20,
			description: 'Lined Anorak',
		},
		{
			name: 'Nike Winderunner',
			slug: 'nike-winderunner',
			category: 'Running Jacket',
			image: '/Images/runner2.webp',
			price: 60,
			rating: 4.8,
			numReviews: 3,
			countInStock: 20,
			description: 'Running Jacket',
		},
		{
			name: 'Nike Runner',
			slug: 'nike-runner',
			category: 'Running Jacket',
			image: '/Images/runner3.webp',
			price: 96,
			rating: 4.8,
			numReviews: 3.5,
			countInStock: 20,
			description: 'Running Jacket',
		},
		{
			name: 'Nike Sportswear Therma-FIT',
			slug: 'nike-sportswear-therma-fit',
			category: 'Hooded Jacket',
			image: '/Images/Hooded1.webp',
			price: 129,
			rating: 5,
			numReviews: 3,
			countInStock: 20,
			description: 'Hooded Jacket',
		},
	],
};

export default data;
